@startuml
title: ApplicationSync
footer: Common Gateway Plugin | {repo_owner} | {repo_name} 
header: Schema

class ApplicationSync {
  + name: string
  + shortDescription: string
  + description: string
  + detailPageImageUrl: string
  + documentationUrl: string
  + demoUrl: string
  + bpmnProcessUrl: string
  + isPublished: boolean
  + owner: array
  + components: array
}
@enduml
