@startuml
title: Catalogi
footer: Common Gateway Plugin | Opencatalogi | Opencatalogibundle 
header: Schema

class Catalogi {
  + source: Any
  + organisation: Any
  + rsin: string
  + pki: string
}
@enduml
