@startuml
title: Commonground
footer: Common Gateway Plugin | {repo_owner} | {repo_name} 
header: Schema

class Commonground {
  + intendedOrganisations: array
  + installationType: string
  + layerType: string
}
@enduml
