@startuml
title: Description
footer: Common Gateway Plugin | Opencatalogi | Opencatalogibundle 
header: Schema

class Description {
  + id: string
  + localisedName: string
  + shortDescription: string
  + longDescription: string
  + documentation: string
  + apiDocumentation: string
  + features: array
  + screenshots: array
  + videos: array
  + awards: array
}
@enduml
