@startuml
title: Gemma
footer: Common Gateway Plugin
header: Schema

class Gemma {
  + bedrijfsfuncties: array
  + bedrijfsservices: array
  + applicatiefunctie: string
  + model: string
  + referentieComponenten: array
}
@enduml
