@startuml
title: Installation
footer: Common Gateway Plugin | {repo_owner} | {repo_name} 
header: Schema

class Installation {
  + organization: string
  + component: string
  + version: string
  + environment: string
}
@enduml
