@startuml
title: Installation
footer: Common Gateway Plugin | Opencatalogi | Opencatalogibundle 
header: Schema

class Installation {
  + organization: string
  + component: string
  + version: string
  + environment: string
}
@enduml
