@startuml
title: IntendedAudience
footer: Common Gateway Plugin | Opencatalogi | Opencatalogibundle 
header: Schema

class IntendedAudience {
  + countries: array
  + unsupportedCountries: array
  + scope: array
}
@enduml
