@startuml
title: Legal
footer: Common Gateway Plugin | {repo_owner} | {repo_name} 
header: Schema

class Legal {
  + license: string
  + mainCopyrightOwner: Any
  + repoOwner: Any
  + authorsFile: string
}
@enduml
