@startuml
title: Maintenance
footer: Common Gateway Plugin | Opencatalogi | Opencatalogibundle 
header: Schema

class Maintenance {
  + type: string
  + contractors: array
  + contacts: array
}
@enduml
