@startuml
title: Organisation
footer: Common Gateway Plugin
header: Schema

class Organisation {
  + name: string
  + description: string
  + logo: string
  + supports: array
  + owns: array
  + uses: array
  + token: string
  + github: string
  + gitlab: string
  + website: string
  + phone: string
  + email: string
  + type: string
  + catalogusAPI: string
}
@enduml
